//
//  CurrencyDetailInterfaces.swift
//  CryptoTracker
//
//  Created by merengue on 18/03/2018.
//  Copyright (c) 2018 merengue. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum CurrencyDetailNavigationOption {
}

protocol CurrencyDetailWireframeInterface: WireframeInterface {
    func navigate(to option: CurrencyDetailNavigationOption)
}

protocol CurrencyDetailViewInterface: ViewInterface {
}

protocol CurrencyDetailPresenterInterface: PresenterInterface {
    func loadHistory(for currency: Currency)
}

protocol CurrencyDetailInteractorInterface: InteractorInterface {
    func loadHistory(for currency: Currency, onResult: @escaping (CurrencyHistoryResponse) -> Void)
}
