//
//  CurrencyDetailPresenter.swift
//  CryptoTracker
//
//  Created by merengue on 18/03/2018.
//  Copyright (c) 2018 merengue. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CurrencyDetailPresenter {

    // MARK: - Private properties -

    private unowned var _view: CurrencyDetailViewInterface
    private var _interactor: CurrencyDetailInteractorInterface
    private var _wireframe: CurrencyDetailWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: CurrencyDetailWireframeInterface, view: CurrencyDetailViewInterface, interactor: CurrencyDetailInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
    
    private func hideLoadingView() {
        self._wireframe.dismiss(animated: true)
    }
}

// MARK: - Extensions -

extension CurrencyDetailPresenter: CurrencyDetailPresenterInterface {
    func loadHistory(for currency: Currency) {
        _wireframe.showLoadingView()
        _interactor.loadHistory(for: currency) { (response) in
            DispatchQueue.main.async {
                self._view.updateHistory(with: response)
            }
            DispatchQueue.main.asyncAfter(deadline: .now() + 2.0, execute: {
                self.hideLoadingView()
            })
        }
    }
}
