//
//  CurrencyDetailViewController.swift
//  CryptoTracker
//
//  Created by merengue on 18/03/2018.
//  Copyright (c) 2018 merengue. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CurrencyDetailViewController: UIViewController, CurrencyHistoryChartDelegate {
    
    var entries: [(Int, Double)] = []
    
    var currency: Currency!

    // MARK: - Public properties -

    var presenter: CurrencyDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.loadHistory(for: currency)
    }
    
    private func addCurrencyHistoryChart() {
        let chart = CurrencyHistoryChart(frame: CGRect(x: 0.0, y: 0.0, width: self.view.frame.width, height: self.view.frame.height))
        chart.delegate = self
        self.view.addSubview(chart)
    }
	
}

// MARK: - Extensions -

extension CurrencyDetailViewController: CurrencyDetailViewInterface {
    func updateHistory(with response: CurrencyHistoryResponse) {
        entries = response.currencyHistoryValues.map({ (historyValue) -> (Int, Double) in
            return (historyValue.time, historyValue.close)
        })
        addCurrencyHistoryChart()
    }
}
