//
//  CurrencyDetailViewController.swift
//  CryptoTracker
//
//  Created by merengue on 18/03/2018.
//  Copyright (c) 2018 merengue. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CurrencyDetailViewController: UIViewController {
    
    var currency: Currency!

    // MARK: - Public properties -

    var presenter: CurrencyDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.loadHistory(for: currency)
    }
	
}

// MARK: - Extensions -

extension CurrencyDetailViewController: CurrencyDetailViewInterface {
}
