//
//  CryptocurrencyInteractor.swift
//  CryptoTracker
//
//  Created by merengue on 17/03/2018.
//  Copyright (c) 2018 merengue. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class CurrenciesInteractor {
    private let apiClient = APIClient()
    private let disposeBag = DisposeBag()
    
    private static let currenciesBaseURL = URL(string: "https://api.coinmarketcap.com/")!
}

// MARK: - Extensions -

extension CurrenciesInteractor: CurrenciesInteractorInterface {
    func loadCurrencies(onResult: @escaping ([Currency]) -> Void) {
        Observable
            .just(CurrenciesRequest())
            .flatMap { (request) -> Observable<[Currency]> in
                return self.apiClient.send(apiRequest: request, url: CurrenciesInteractor.currenciesBaseURL)
            }
            .subscribe { (event) in
                guard let data = event.element else {
                    print("No data.")
                    return
                }
                onResult(data)
            }
            .disposed(by: disposeBag)
    }
}
