//
//  CryptocurrencyWireframe.swift
//  CryptoTracker
//
//  Created by merengue on 17/03/2018.
//  Copyright (c) 2018 merengue. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CurrenciesWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Currencies", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: CurrenciesViewController) {
        let interactor = CurrenciesInteractor()
        let presenter = CryptocurrencyPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: CurrenciesViewController.self)
        configureModule(with: moduleViewController)

        show(moduleViewController, with: transition, animated: animated)
    }
    
    private func openCurrencyDetail(currency: Currency) {
        let wireframe = CurrencyDetailWireframe(navigationController: navigationController)
        wireframe.show(with: .push, currency: currency)
    }
}

// MARK: - Extensions -

extension CurrenciesWireframe: CurrenciesWireframeInterface {

    func navigate(to option: CurrenciesNavigationOption) {
        switch option {
        case .currencyDetail(let currency):
            openCurrencyDetail(currency: currency)
        }
    }
    
    
}
