//
//  CryptocurrencyPresenter.swift
//  CryptoTracker
//
//  Created by merengue on 17/03/2018.
//  Copyright (c) 2018 merengue. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CryptocurrencyPresenter {

    // MARK: - Private properties -

    private unowned var _view: CurrenciesViewInterface
    private var _interactor: CurrenciesInteractorInterface
    private var _wireframe: CurrenciesWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: CurrenciesWireframeInterface, view: CurrenciesViewInterface, interactor: CurrenciesInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension CryptocurrencyPresenter: CurrenciesPresenterInterface {
    func loadCurrencies() {
        _wireframe.showLoadingView()
        _interactor.loadCurrencies { (currencies) in
            let sorted = currencies.sortedByPriceUSD()
            self._view.updateCurrencies(sorted)
            self._wireframe.dismiss(animated: true)
        }
    }
    
    func openCurrencyDetail(for currency: Currency) {
        _wireframe.navigate(to: .currencyDetail(currency: currency))
    }
}
